### ISSUE TITLE
how i can use

### ISSUE THREAD

**Issue by viptv** [Joe11000/Troll-Starver-for-Youtube-Live-Chat#2]
Your script ?

**Comment by Joe11000** [comment]
There is a video demo on my chrome extension here.
https://chrome.google.com/webstore/detail/youtube-live-chat-troll-s/bcikajlocgcppeihfloalfdnpgfibdpk

Basic steps are 1) download the chrome extension 2) visit a live streamed video with a chatroom and click the green troll icon (to the right of the search bar)

**Comment by viptv** [comment]
cool

**Comment by Joe11000** [comment]
Here is the instructional demo video google is failing to display.
https://www.youtube.com/watch?v=cCrwyIKI_Jo

Where my video is suppose to be displayed for my chrome extension, google is throwing this error.... That is kind of annoying and makes my extension look bad.
<img width="1440" alt="screen shot 2017-02-23 at 6 37 28 pm" src="https://cloud.githubusercontent.com/assets/4231108/23285511/38771e12-f9f7-11e6-979e-e5d14cde2ce1.png">
